name: 藏经发现
description: 发现了新的大藏经资源，需要大家群策群力下载。
title: "[藏经发现]: "
labels: ["藏经发现"]
body:
  - type: input
    id: "url"
    attributes:
      label: "原站地址"
      description: "大藏经原始的地址"
    validations:
      required: true
  - type: textarea
    id: "describe"
    attributes:
      label: "具体说明"
      description: "详细描述具体情况"
    validations:
      required: true
